spring:
  application:
    name: psd-start-information-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: https://app-8b2a441b-b715-4698-9cd5-a9305dcc7ab2.cleverapps.io/