spring:
  application:
    name: psd-start-information-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: https://app-43b27924-768c-4500-a4cf-81b16707471a.cleverapps.io/